/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApprovalRequestDTO { 
    flagEdvPermission?: boolean;
    flagFurniturePermission?: boolean;
    flagFurnitureRoom?: boolean;
    flagInvestmentRoom?: boolean;
    flagInvestmentStructuralMeasures?: boolean;
    flagMediaPermission?: boolean;
}

