/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApprovalResponseDTO { 
    order_id?: number;
    flag_edv_permission?: boolean;
    flag_furniture_permission?: boolean;
    flag_furniture_room?: boolean;
    flag_investment_room?: boolean;
    flag_investment_structural_measures?: boolean;
    flag_media_permission?: boolean;
}

