/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ItemRequestDTO { 
    name: string;
    price_per_unit: number;
    quantity: number;
    quantity_unit?: string;
    article_id?: string;
    comment?: string;
    vat_value: string;
    preferred_list?: ItemRequestDTO.PreferredListEnum;
    preferred_list_number?: string;
    vat_type: ItemRequestDTO.VatTypeEnum;
}
export namespace ItemRequestDTO {
    export const PreferredListEnum = {
        RZ: 'RZ',
        TA: 'TA'
    } as const;
    export type PreferredListEnum = typeof PreferredListEnum[keyof typeof PreferredListEnum];
    export const VatTypeEnum = {
        NETTO: 'netto',
        BRUTTO: 'brutto'
    } as const;
    export type VatTypeEnum = typeof VatTypeEnum[keyof typeof VatTypeEnum];
}


