/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderStatus = {
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    ApprovalsReceived: 'APPROVALS_RECEIVED',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Sent: 'SENT',
    Settled: 'SETTLED',
    Archived: 'ARCHIVED',
    Deleted: 'DELETED'
} as const;
export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];

