/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderStatus = {
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    APPROVALS_RECEIVED: 'APPROVALS_RECEIVED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    SENT: 'SENT',
    SETTLED: 'SETTLED',
    ARCHIVED: 'ARCHIVED',
    DELETED: 'DELETED'
} as const;
export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];

