/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderResponseDTO } from './orderResponseDTO';
import { Sort } from './sort';
import { PagedOrderResponseDTOPageable } from './pagedOrderResponseDTOPageable';


export interface PagedOrderResponseDTO { 
    content?: Array<OrderResponseDTO>;
    pageable?: PagedOrderResponseDTOPageable;
    last?: boolean;
    total_pages?: number;
    total_elements?: number;
    size?: number;
    number?: number;
    sort?: Sort;
    first?: boolean;
    number_of_elements?: number;
    empty?: boolean;
}

