/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PreferenceType = {
    ORDER_PRESETS: 'ORDER_PRESETS'
} as const;
export type PreferenceType = typeof PreferenceType[keyof typeof PreferenceType];

