/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuotationResponseDTO { 
    index?: number;
    quote_date?: string;
    price?: number;
    company_name?: string;
    company_city?: string;
}

