/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreferenceType } from './preferenceType';


export interface UserPreferencesRequestDTO { 
    preference_type: PreferenceType;
    preferences: { [key: string]: any; };
}
export namespace UserPreferencesRequestDTO {
}


