/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPreferencesResponseDTO { 
    id: number;
    preference_type: string;
    preferences: { [key: string]: any; };
}

