export const orderDisplayNames: Record<string, string> = {
    id: 'ID',
    primary_cost_center_id: 'Primary Cost Center ID',
    booking_year: 'Booking Year',
    auto_index: 'Auto Index',
    created_date: 'Created Date',
    legacy_alias: 'Legacy Alias',
    owner_id: 'Owner ID',
    content_description: 'Content Description',
    status: 'Status',
    currency_short: 'Currency Short',
    comment: 'Comment',
    comment_for_supplier: 'Comment for Supplier',
    quote_number: 'Quote Number',
    quote_sign: 'Quote Sign',
    quote_date: 'Quote Date',
    quote_price: 'Quote Price',
    delivery_person_id: 'Delivery Person ID',
    invoice_person_id: 'Invoice Person ID',
    queries_person_id: 'Queries Person ID',
    customer_id: 'Customer ID',
    supplier_id: 'Supplier ID',
    secondary_cost_center_id: 'Secondary Cost Center ID',
    fixed_discount: 'Fixed Discount',
    percentage_discount: 'Percentage Discount',
    cash_discount: 'Cash Discount',
    cashback_days: 'Cashback Days',
    last_updated_time: 'Last Updated Time',
    flag_decision_cheapest_offer: 'Decision Cheapest Offer',
    flag_decision_sole_supplier: 'Decision Sole Supplier',
    flag_decision_contract_partner: 'Decision Contract Partner',
    flag_decision_other_reasons: 'Decision Other Reasons',
    decision_other_reasons_description: 'Decision Other Reasons Description',
    flag_edv_permission: 'EDV Permission',
    flag_furniture_permission: 'Furniture Permission',
    flag_furniture_room: 'Furniture Room',
    flag_investment_room: 'Investment Room',
    flag_investment_structural_measures: 'Investment Structural Measures',
    flag_media_permission: 'Media Permission',
    dfg_key: 'DFG Key'
};
