/**
 * Centralized mapping of order field keys to their display labels.
 * Used for table columns and other UI elements.
 */
export const ORDER_FIELD_NAMES: Record<string, string> = {
  id: 'BeSy ID',
  besy_number: 'Bestellnummer',
  status: 'Status',
  content_description: 'Beschreibung',
  primary_cost_center_id: 'Kostenstelle',
  supplier_id: 'Lieferant',
  last_updated_time: 'Änderungsdatum',
  auto_index: 'Auto-Index',
  legacy_alias: 'Alte Bezeichnung',
  currency: 'Währung',
  comment: 'Kommentar',
  comment_for_supplier: 'Kommentar an Lieferanten',
  quote_number: 'Angebotsnummer',
  quote_sign: 'Angebotszeichen',
  quote_date: 'Angebotsdatum',
  fixed_discount: 'Fixrabatt',
  percentage_discount: 'Prozentualer Rabatt',
  cashback_percentage: 'Cashback Prozentsatz',
  cash_discount: 'Skonto',
  cashback_days: 'Skontotage',
  flag_decision_cheapest_offer: 'Günstigstes Angebot',
  flag_decision_most_economical_offer: 'Wirtschaftlichstes Angebot',
  flag_decision_sole_supplier: 'Einziger Lieferant',
  flag_decision_contract_partner: 'Vertragspartner',
  flag_decision_preferred_supplier_list: 'Lieferanten aus der Vorzugsliste',
  flag_decision_other_reasons: 'Sonstiger Grund',
  decision_other_reasons_description: 'Begründung für sonstigen Grund',
  dfg_key: 'DFG-Schlüssel',
  booking_year: 'Buchungsjahr',
  created_date: 'Erstellt am',
  owner_id: 'Erstellt von',
  quote_price: 'Preis',
  delivery_person_id: 'Bestellt für',
  invoice_person_id: 'Rechnungsempfänger:in',
  queries_person_id: 'Ansprechperson',
  customer_id: 'Kundennummer',
  secondary_cost_center_id: 'Sekundäre Kostenstelle',
  delivery_address_id: 'Lieferadresse',
  invoice_address_id: 'Rechnungsadresse',
};
