/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceResponseDTO { 
    id?: string;
    cost_center_id?: string;
    order_id?: number;
    price?: number;
    date?: string;
    comment?: string;
    created_date?: string;
    paperless_id?: number;
}

