/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Datenübertragungsobjekt zur Erstellung einer Rechnung
 */
export interface InvoiceRequestDTO { 
    /**
     * ID der Rechnung
     */
    id: string;
    /**
     * ID der zugehörigen Kostenstelle
     */
    cost_center_id: number;
    /**
     * Referenz auf die zugehörige Bestellung
     */
    order_id: number;
    /**
     * Rechnungsbetrag
     */
    price: number;
    /**
     * Rechnungsdatum
     */
    date: string;
    /**
     * Kommentar zur Rechnung
     */
    comment?: string;
    /**
     * Referenz auf ein Dokument im papierlosen System
     */
    paperless_id?: number;
}

