/**
 * Bestellsystem API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonRequestDTO { 
    name: string;
    surname: string;
    email?: string;
    fax?: string;
    phone?: string;
    title?: string;
    comment?: string;
    address_id?: number;
    gender: PersonRequestDTO.GenderEnum;
}
export namespace PersonRequestDTO {
    export const GenderEnum = {
        M: 'm',
        F: 'f',
        D: 'd'
    } as const;
    export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];
}


